import { defineTextStyles } from "@pandacss/dev";

export const textStyles = defineTextStyles({
  "Title/60px.700": {
    description: "Large title text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "60px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "72px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/40px/40px.400": {
    description: "Medium title text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "40px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "52px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/40px/40px.700": {
    description: "Medium title text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "40px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "52px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/32px/32px.400": {
    description: "Small title text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "32px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "42px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/32px/32px.700": {
    description: "Small title text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "32px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "42px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/24px/24px.400": {
    description: "Subtitle text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "24px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "34px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/24px/24px.700": {
    description: "Subtitle text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "24px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "34px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/18px/18px.400": {
    description: "Small subtitle text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "18px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "26px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Title/18px/18px.700": {
    description: "Small subtitle text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "18px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "26px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/16px/16px.400": {
    description: "Default body text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "24px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/16px/16px.500": {
    description: "Default body text with medium weight",
    value: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "500",
      letterSpacing: "-0.4px",
      lineHeight: "24px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/16px/16px.700": {
    description: "Default body text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "24px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/14px/14px.400": {
    description: "Small body text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "20px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/14px/14px.500": {
    description: "Small body text with medium weight",
    value: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: "500",
      letterSpacing: "-0.4px",
      lineHeight: "20px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/14px/14px.700": {
    description: "Small body text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "20px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/12px/12px.400": {
    description: "Extra small body text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "16px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/12px/12px.500": {
    description: "Extra small body text with medium weight",
    value: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "500",
      letterSpacing: "-0.4px",
      lineHeight: "16px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "Body/12px/12px.700": {
    description: "Extra small body text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "16px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
});
